Jan 16, Wed 19:20:56,427 - DeviceService - INFO - Init
Jan 16, Wed 19:20:56,598 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 19:20:56,614 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 19:20:59,19 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 19:20:59,19 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 19:21:02,453 - django.request - WARNING - Not Found: /favicon.ico
Jan 16, Wed 20:16:14,711 - DeviceService - INFO - Init
Jan 16, Wed 20:16:14,747 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 20:16:14,752 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 20:16:16,543 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 20:16:16,545 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 20:16:18,336 - django.request - WARNING - Not Found: /favicon.ico
Jan 16, Wed 20:18:38,369 - django.request - WARNING - Not Found: /favicon.ico
Jan 16, Wed 20:37:39,190 - DeviceService - INFO - Init
Jan 16, Wed 20:37:39,249 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 20:37:39,256 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 20:37:39,657 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 20:37:39,657 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 20:40:27,247 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 20:43:06,269 - django.request - ERROR - Internal Server Error: /controls
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\ControlController.py", line 16, in post
    control = self.__controlRepo.Save(request.data)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ControlRepository.py", line 50, in Save
    condition = self.__conditionRepo.Save(conditionDict)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ConditionRepository.py", line 61, in Save
    model.save()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\models.py", line 129, in save
    return super(Condition, self).save(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 902, in _save_table
    for f in non_pks]
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1432, in pre_save
    return super(DateTimeField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1280, in pre_save
    return super(DateField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 745, in pre_save
    return getattr(model_instance, self.attname)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query_utils.py", line 116, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 697, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Condition matching query does not exist.
Jan 16, Wed 20:47:22,608 - django.request - ERROR - Internal Server Error: /controls
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\ControlController.py", line 16, in post
    control = self.__controlRepo.Save(request.data)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ControlRepository.py", line 50, in Save
    condition = self.__conditionRepo.Save(conditionDict)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ConditionRepository.py", line 61, in Save
    model.save()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\models.py", line 129, in save
    return super(Condition, self).save(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 902, in _save_table
    for f in non_pks]
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1432, in pre_save
    return super(DateTimeField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1280, in pre_save
    return super(DateField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 745, in pre_save
    return getattr(model_instance, self.attname)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query_utils.py", line 116, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 697, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Condition matching query does not exist.
Jan 16, Wed 20:47:50,755 - django.request - ERROR - Internal Server Error: /controls
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\ControlController.py", line 16, in post
    control = self.__controlRepo.Save(request.data)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ControlRepository.py", line 50, in Save
    condition = self.__conditionRepo.Save(conditionDict)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ConditionRepository.py", line 61, in Save
    model.save()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\models.py", line 129, in save
    return super(Condition, self).save(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 902, in _save_table
    for f in non_pks]
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1432, in pre_save
    return super(DateTimeField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1280, in pre_save
    return super(DateField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 745, in pre_save
    return getattr(model_instance, self.attname)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query_utils.py", line 116, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 697, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Condition matching query does not exist.
Jan 16, Wed 20:48:51,716 - DeviceService - INFO - Init
Jan 16, Wed 20:48:51,773 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 20:48:51,789 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 20:48:52,164 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 20:48:52,165 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 20:49:26,2 - django.request - ERROR - Internal Server Error: /controls
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\ControlController.py", line 16, in post
    control = self.__controlRepo.Save(request.data)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ControlRepository.py", line 50, in Save
    condition = self.__conditionRepo.Save(conditionDict)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ConditionRepository.py", line 61, in Save
    model.save()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\models.py", line 129, in save
    return super(Condition, self).save(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 902, in _save_table
    for f in non_pks]
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1432, in pre_save
    return super(DateTimeField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1280, in pre_save
    return super(DateField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 745, in pre_save
    return getattr(model_instance, self.attname)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query_utils.py", line 116, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 697, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Condition matching query does not exist.
Jan 16, Wed 20:50:39,341 - django.request - ERROR - Internal Server Error: /controls
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\ControlController.py", line 16, in post
    control = self.__controlRepo.Save(request.data)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ControlRepository.py", line 50, in Save
    condition = self.__conditionRepo.Save(conditionDict)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ConditionRepository.py", line 61, in Save
    model.save()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\models.py", line 129, in save
    return super(Condition, self).save(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 902, in _save_table
    for f in non_pks]
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1432, in pre_save
    return super(DateTimeField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1280, in pre_save
    return super(DateField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 745, in pre_save
    return getattr(model_instance, self.attname)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query_utils.py", line 116, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 697, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Condition matching query does not exist.
Jan 16, Wed 20:50:55,73 - django.request - ERROR - Internal Server Error: /controls
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\ControlController.py", line 16, in post
    control = self.__controlRepo.Save(request.data)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ControlRepository.py", line 50, in Save
    condition = self.__conditionRepo.Save(conditionDict)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Repositories\ConditionRepository.py", line 61, in Save
    model.save()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\models.py", line 129, in save
    return super(Condition, self).save(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 902, in _save_table
    for f in non_pks]
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1432, in pre_save
    return super(DateTimeField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1280, in pre_save
    return super(DateField, self).pre_save(model_instance, add)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\fields\__init__.py", line 745, in pre_save
    return getattr(model_instance, self.attname)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query_utils.py", line 116, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\base.py", line 697, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Condition matching query does not exist.
Jan 16, Wed 20:52:32,96 - DeviceService - INFO - Init
Jan 16, Wed 20:52:32,117 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 20:52:32,117 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 20:52:32,371 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 20:52:32,371 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 20:53:40,312 - PropertyService - INFO - SaveObject is called with object=Renk (LYYiyPwxNiur6tENsqmjzh); value=rgba(12,180,22,0.88)
Jan 16, Wed 20:54:05,111 - PropertyService - INFO - SaveObject is called with object=Renk (LYYiyPwxNiur6tENsqmjzh); value=rgba(12,29,180,0.88)
Jan 16, Wed 20:56:48,99 - DeviceService - INFO - Init
Jan 16, Wed 20:56:48,119 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 20:56:48,135 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 20:56:48,377 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 20:56:48,378 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:00:19,880 - DeviceService - INFO - Init
Jan 16, Wed 21:00:19,900 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:00:19,900 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:00:20,151 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:00:20,151 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:01:09,926 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:02:32,361 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, property.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:03:31,155 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:05:22,657 - DeviceService - INFO - Init
Jan 16, Wed 21:05:22,707 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:05:22,707 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:05:22,911 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:05:22,911 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:05:30,500 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:05:30,519 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Object)
AttributeError: 'Property' object has no attribute 'Object'
Jan 16, Wed 21:05:33,898 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:05:33,911 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Object)
AttributeError: 'Property' object has no attribute 'Object'
Jan 16, Wed 21:05:39,956 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:05:39,974 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Object)
AttributeError: 'Property' object has no attribute 'Object'
Jan 16, Wed 21:05:54,341 - DeviceService - INFO - Init
Jan 16, Wed 21:05:54,361 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:05:54,361 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:05:54,611 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:05:54,612 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:05:57,117 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:07:10,868 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, property.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:07:22,772 - DeviceService - INFO - Init
Jan 16, Wed 21:07:22,786 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:07:22,792 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:07:23,26 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:07:23,28 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:07:31,457 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:08:01,954 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:09:49,280 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:09:49,306 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:09:54,845 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:09:54,869 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:10:05,177 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:10:05,200 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:10:27,963 - DeviceService - INFO - Init
Jan 16, Wed 21:10:27,983 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:10:27,983 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:10:28,232 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:10:28,232 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:10:35,506 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:17:52,822 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:18:04,55 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:18:04,81 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:18:20,592 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:18:20,618 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:18:22,279 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:18:22,318 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:18:23,463 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:18:23,486 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:18:28,897 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:18:28,930 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.Compare(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in Compare
    return self.Compare(property.Class, condition.Value, condition.Operator, otherValue)
TypeError: Compare() takes exactly 3 arguments (5 given)
Jan 16, Wed 21:18:36,704 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:22:13,194 - DeviceService - INFO - Init
Jan 16, Wed 21:22:13,209 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:22:13,224 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:22:13,464 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:22:13,464 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:22:18,384 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:22:44,197 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.CompareCondition(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in CompareCondition
    return self.CompareValue(property.Class, condition.Value, condition.Operator, otherValue)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 44, in CompareValue
    compare = getattr(comparator, operator)
TypeError: getattr(): attribute name must be string
Jan 16, Wed 21:22:57,351 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:23:16,855 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.CompareCondition(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in CompareCondition
    return self.CompareValue(property.Class, condition.Value, condition.Operator, otherValue)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 44, in CompareValue
    compare = getattr(comparator, operator)
TypeError: getattr(): attribute name must be string
Jan 16, Wed 21:23:29,167 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:25:10,956 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 42, in __isSatisfied
    satisfied = comparator.CompareCondition(condition, property.Value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 53, in CompareCondition
    return self.CompareValue(property.Class, condition.Value, condition.Operator, otherValue)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\ValueComparator.py", line 44, in CompareValue
    compare = getattr(comparator, operator)
TypeError: getattr(): attribute name must be string
Jan 16, Wed 21:25:14,545 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:36:39,888 - DeviceService - INFO - Init
Jan 16, Wed 21:36:39,907 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:36:39,924 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:36:40,161 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:36:40,163 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:36:43,934 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:40:16,819 - DeviceService - INFO - Init
Jan 16, Wed 21:40:16,834 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:40:16,838 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:40:17,81 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:40:17,82 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:40:22,711 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 21:45:53,157 - DeviceService - INFO - Init
Jan 16, Wed 21:45:53,177 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 21:45:53,177 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 21:45:53,408 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 21:45:53,408 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 21:45:57,684 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 21:48:28,132 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:06:12,671 - DeviceService - INFO - Init
Jan 16, Wed 22:06:12,730 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 22:06:12,734 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 22:06:13,151 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 22:06:13,151 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 22:06:30,122 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:09:23,259 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:11:40,855 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 45, in __isSatisfied
    for andCondition in condition.AndConditions:
TypeError: 'ManyRelatedManager' object is not iterable
Jan 16, Wed 22:12:29,454 - DeviceService - INFO - Init
Jan 16, Wed 22:12:29,474 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 22:14:35,752 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 22:15:37,142 - DeviceService - INFO - Init
Jan 16, Wed 22:15:37,164 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 22:15:42,562 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 22:15:42,799 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 22:15:42,799 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 22:16:39,315 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:21:30,838 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:22:26,796 - DeviceService - INFO - Init
Jan 16, Wed 22:22:26,816 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 22:22:39,111 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 22:22:39,338 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 22:22:39,338 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 22:22:51,709 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:23:13,559 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:23:30,424 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 45, in __isSatisfied
    for andCondition in set(condition.AndConditions):
TypeError: 'ManyRelatedManager' object is not iterable
Jan 16, Wed 22:25:32,803 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:25:37,479 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:26:29,994 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 32, in NotifyConditions
    if not self.__isSatisfied(condition):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 45, in __isSatisfied
    for andCondition in set(condition.AndConditions):
TypeError: 'ManyRelatedManager' object is not iterable
Jan 16, Wed 22:26:40,823 - DeviceService - INFO - Init
Jan 16, Wed 22:26:40,844 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 22:26:40,844 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 22:26:41,86 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 22:26:41,86 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 22:26:44,430 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:26:46,382 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:27:29,658 - django.request - ERROR - Internal Server Error: /interfaces
Traceback (most recent call last):
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\rest_framework\views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\Controllers\InterfaceController.py", line 31, in put
    result = self.__interfaceService.CallEditor(interface,value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\InterfaceService.py", line 25, in CallEditor
    return self.__deviceService.SetProperty(model.Editor.Id, object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\DeviceService.py", line 55, in SetProperty
    return callFunction(**kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 34, in Toggle
    self.__State(pin, not currentState)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 28, in __State
    return self.State(**parameters)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 20, in State
    pinObject.Status = value
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\IOExtender.py", line 88, in Status
    self.SetValue(self.Properties.filter(CallFunction='State').first(), value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\HardwareServices\BaseFunctionService.py", line 14, in SetValue
    return self._propertyService.SaveObject(property, value)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\PropertyService.py", line 39, in SaveObject
    self.__conditionService.NotifyConditionsOfProperty(object)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 29, in NotifyConditionsOfProperty
    self.NotifyConditions(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 34, in NotifyConditions
    self.__callTasks(condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\app\DatabaseServices\ConditionService.py", line 52, in __callTasks
    controls = Control.objects.filter(Condition=condition)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\sql\query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\sql\query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\sql\query.py", line 1154, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\sql\query.py", line 1034, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Users\leven\Documents\GitHub\DjangoHome\venv\lib\site-packages\django\db\models\sql\query.py", line 1352, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'Condition' into field. Choices are: Conditions, CreatedOn, Id, ModifiedOn, Name, Tasks
Jan 16, Wed 22:29:10,911 - DeviceService - INFO - Init
Jan 16, Wed 22:29:10,926 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 22:29:10,930 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 22:29:11,171 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 22:29:11,171 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 22:29:13,822 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:29:14,733 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:30:25,73 - DeviceService - INFO - Init
Jan 16, Wed 22:30:25,94 - DeviceFactory - INFO - Producing Wallwasher 1 (BVgWGjqNt22Ld5SgoqbZq8) device
Jan 16, Wed 22:30:25,109 - DeviceFactory - INFO - Producing Role Modülü 1 (Y7nVZ5G6gEMtaektRAuQTo) device
Jan 16, Wed 22:30:25,332 - MARKDOWN - DEBUG - Successfuly imported extension module "markdown.extensions.toc".
Jan 16, Wed 22:30:25,332 - MARKDOWN - DEBUG - Successfully loaded extension "markdown.extensions.toc.TocExtension".
Jan 16, Wed 22:30:28,42 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:30:29,638 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
Jan 16, Wed 22:39:28,936 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=True
Jan 16, Wed 22:39:30,605 - PropertyService - INFO - SaveObject is called with object=Durum (4YpAdzqfKpJnEvaHpD4ZnY); value=False
